steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240523-a15ad90fc9
    env:
      - REGISTRY=gcr.io/k8s-staging-ingress-nginx
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker && cd images && make NAME=go-grpc-greeter-server push
